services:
  todo_list_client:
    build: client
    image: todolist-client
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    ports:
      - 5173:5173
    depends_on:
      - todo_list_server

  todo_list_server:
    build: server
    image: todolist-server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - project.env
    depends_on:
      - todo_list_database

  todo_list_database:
    container_name: postgresql_todo_list_database
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - project.env

  todo_list_database-migrations:
    image: flyway/flyway:10
    env_file:
      - project.env
    depends_on:
      - todo_list_database
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
        
#  e2e-tests:
#    entrypoint: "/bin/true"
#    build: e2e-tests
#    network_mode: host
#    depends_on:
#      - client
#    volumes:
#      - ./e2e-tests/tests:/app/tests
